version: "3"

services:
    # redis:
    #     image: redis
    #     container_name: redis
    #     ports:
    #         - "6379:6379"
    #     networks:
    #         - gateway

    # mongo:
    #     image: mongo:3
    #     container_name: mongo
    #     command: mongod --smallfiles --bind_ip_all
    #     volumes:
    #         - ./data:/data/db
    #     ports:
    #         - "27017:27017"
    #     networks:
    #         - gateway

    connection:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: connection
        ports:
            - "3069:3069"
        networks:
            - gateway
        environment:
            SERVICE_PORT: 3069
            SERVICE_NAME: connection

networks:
    gateway:
